name: Backend Unit Tests
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      -   name: Checkout
          uses: actions/checkout@v4

      -   name: Setup .NET Core
          uses: actions/setup-dotnet@v2
          with:
            dotnet-version: '9.x'

      -   name: Install dependencies
          run: dotnet restore

      -   name: Build
          run: dotnet build --no-restore

      -   name: Run tests
          run: dotnet test --no-build --verbosity normal